# Generated by Django 3.0.4 on 2022-01-20 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.CharField(max_length=10, verbose_name='水费')),
                ('electricity', models.CharField(max_length=20, verbose_name='电费')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Room', verbose_name='宿舍号')),
            ],
            options={
                'verbose_name': '水电',
                'verbose_name_plural': '水电',
            },
        ),
    ]
